import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'
import Header from './components/header/Header'
import './globals.css'

const mulish = Mulish({
	weight: ['200', '300', '400', '500', '600', '700'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={mulish.className}>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	)
}
